[package]
name = "samsara"
version = "0.1.0"
edition = "2018"

[dependencies]
miette = {version = "3.1.0", features = ["fancy"]}
petgraph = {version = "0.6.0", default-features = false}
lazy_static = "1.4.0"
parking_lot = "0.11.2"

[dev-dependencies]
serial_test = "0.5.1"